version: "3"

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: supersecretpassword
      PGDATA: /var/lib/postgresql/data

  app:
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:supersecretpassword@db/diesel
    build: .
    links:
      - db
    command: >
      bash -c "diesel migration run && ./core_rocket"

volumes:
  pgdata: {}
