# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema.default]
file = "core/diesel/tables/schema.rs"

[migrations_directory]
dir = "core/diesel/migrations"