[package]
name = "features"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
chrono = { workspace = true}
rocket = { workspace = true }
diesel = { workspace = true }
core_diesel = { path = "../core/diesel" }

[lib]
path = "lib.rs"